version: '3'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        env_file:
            - .env
    scheduler:
        build: .
        command: scheduler
        env_file:
            - .env
        depends_on:
            - postgres
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
        healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3
    webserver:
        build: .
        entrypoint: /usr/local/airflow/scripts/entrypoint.sh
        env_file:
            - .env
        depends_on:
            - postgres
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
            - ./scripts:/usr/local/airflow/scripts
        ports:
            - "8080:8080"
        healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3